alias §='cd /mnt/c/Users/emrah.kaya'
alias gs='git status'
alias gl='git log --oneline --all --graph --decorate'
alias gitwrecked='git reset HEAD --hard'
alias e.='explorer.exe .'
alias vsclean='rm -rf ./**/bin && rm -rf ./**/obj && rm -rf packages/'
